#!/usr/bin/env sh

#set the time zone
ln -sf /usr/share/zoneinfo/America/Phoenix /etc/localtime
hwclock --systohc

#generate locales
echo en_US.UTF-8 UTF-8 > /etc/locale.gen
locale-gen
echo LANG=en_US.UTF-8 > /etc/locale.conf

#sudo tweaks
echo "%wheel ALL=(ALL:ALL) ALL" > /etc/sudoers.d/00-wheel-can-sudo
echo "Defaults editor=/usr/bin/nvim" > /etc/sudoers.d/01-visudo-editor

#pacman tweaks
# This is using sed as find and replace, same syntax as vim
sed -i 's/#Color/Color/' /etc/pacman.conf

pacman -Sy

#Make hostname
read -p 'Enter hostname: ' hostnm 
echo $hostnm > /etc/hostname

#prompt for root password
echo "pick your root password"
passwd 

#setup user account
read -p 'Enter username: ' user
useradd -mG wheel,uucp,network $user
echo "Enter password for account $user"
passwd $user

#install yay
git clone https://aur.archlinux.org/yay.git /home/$user/yay 
pushd /home/$user/yay
chown -R $user .
sudo -u ryan makepkg -si --noconfirm
popd

packageList=""

#Install sway?
read -p "Install sway? [Y/n]" yn
case $yn in
    [Nn]* ) ;;
    * ) packageList="${packageList} $(cat /packageLists/gui.txt)"
        pushd /home/$user; sudo -u $user sh /installDotfiles; popd
        ;;
esac

#Separated package lists in case installing on mobile tether(thanks proprietary drivers)
read -p "Install rest of packages now? [Y/n]" yn
case $yn in
    [Nn]* ) ;;
    * ) packageList="${packageList} $(cat /packageLists/full.txt)"
        ;;
esac

#Are we dual booting? 
read -p "Is this a dual boot installation? [y/N]" yn
case $yn in
    [Yy]* ) packageList="${packageList} os-prober";
            echo GRUB_DISABLE_OS_PROBER=false >> /etc/default/grub;
        ;;
    * ) ;;
esac

read -p "Is this a laptop? [y/N]" yn
case $yn in
    [Yy]* ) packageList="${packageList} brightnessctl acpi sof-firmware";
        ;;
    * ) ;;
esac

read -p "Is this an Intel machine? [y/N]" yn
case $yn in
    [Yy]* ) packageList="${packageList} intel-ucode";
        ;;
    * )     packageList="${packageList} amd-ucode";
        ;;
esac

#get grub downloaded
sudo -u $user yay -S --noconfirm grub efibootmgr ${packageList}

#enable networkmanager
systemctl enable NetworkManager

#Install grub
grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB
grub-mkconfig -o /boot/grub/grub.cfg

# Clean up
cp /packageLists/nonEssentialPackages /home/$user/otherPackages
rm -rf packageLists installDotfiles stage2 /home/$user/yay/
